### ISSUE TITLE
please update for support carthage. thanks :)

### ISSUE THREAD

**Issue by ioacode** [CleverTap/CTNotificationService#12]
Dependency "CTNotificationService" has no shared framework schemes for any of the platforms: iOS

**Comment by Aditi3** [comment]
Hi @ioacode 

Thank you for submitting the feature-request.

We've made the changes to support installation via Carthage in our development branch and have a plan to ship the same in a day or two.

**Comment by ioacode** [comment]
Thanks you 😁👍   @Aditi3
