### ISSUE TITLE
Image not showing in push notification in iOS

### ISSUE THREAD

**Issue by Arun-paramasivam** [CleverTap/CTNotificationService#14]
Hi,
I'm using
- clevertap-react-native (0.4.5):
    - CleverTap-iOS-SDK (~> 3.8.2)
    - React
  - CTNotificationService (0.1.2)

I'm receiving push notifications in both android and ios. But push with images works only on android. In iOS I receive a notification but the image is not shown. The title of the message comes as 'Test Push [modified]'. Some extra data is coming but not sure why the image is not shown. 
Have set the deployment target of the Notification Service Extension file as 10.0. And I'm testing it on iPhone 6 with ios 13.7.
[
![WhatsApp Image 2020-09-26 at 11 16 10 PM](https://user-images.githubusercontent.com/17449780/94347022-77a9d500-004e-11eb-8c25-c6aabc0f5d9b.jpeg)
](url)

_Originally posted by @Arun-paramasivam in https://github.com/CleverTap/CTNotificationService/issues/3#issuecomment-699527109_

**Comment by Aditi3** [comment]
Hi @Arun-paramasivam 

It seems to work rightly. Could you take a look at our [Demo Application](https://github.com/CleverTap/CTNotificationService/tree/master/Example) and verify the integration at your end?

**Comment by Arun-paramasivam** [comment]
Hi @Aditi3  

Thanks for the quick response. Changes made in info.plist as you mentioned in the Demo Application. Now the images are arriving in the push notification.

Closing the issue, Thanks.

**Comment by Arun-paramasivam** [comment]
Hi @Aditi3 

When the archive is made, I get the following errors and warnings

warning:
Target 'Pods-CTNotificationServiceExtension' of project 'Pods' was rejected as an implicit dependency for 'libPods-CTNotificationServiceExtension.a' because its architectures 'arm64' didn't contain all required architectures 'armv7 arm64'

warning:
directory not found for option '-L/Users/user/Library/Developer/Xcode/DerivedData/project-aohgwbgewxccmbdjykjtpkbxkqdp/Build/Intermediates.noindex/ArchiveIntermediates/project/BuildProductsPath/Release-iphoneos/CTNotificationService' 

error:
ld: library not found for -lCTNotificationService

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Satish24sp** [comment]
Hello @Aditi3 , I'm trying to send a push image but it is only showing the notification title and message.
So how can I show the image or media data.
I already added the CTNotificationServiceExtension
I'm using Simulator 17.2.

Please pass some information.
