### ISSUE TITLE
Not able to receive image in notification bar

### ISSUE THREAD

**Issue by dattaprasadPegasus** [CleverTap/CTNotificationService#17]
I have integrated CleverTap having one issue : 
Not able to receive image in notification. Application able to receive text notification but when I tried to send notification with image , able to receive notification but image not showing 

Here is my configuration

"clevertap-react-native": "^0.4.5",

pod file : 
target 'NotificationService' do
  platform :ios, '10.0'
  pod 'CTNotificationService'
end

NotificationService.h
//
//  NotificationService.h
//  NotificationService
//
//  Created by Pegasus on 17/11/20.
//  Copyright © 2020 Facebook. All rights reserved.
//
#import <CTNotificationService/CTNotificationService.h>

@interface NotificationService : CTNotificationServiceExtension

@end

NotificationService.m
#import "NotificationService.h"

@implementation NotificationService

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler {
    
    self.mediaUrlKey = @"myMediaUrlKey";
    self.mediaTypeKey = @"myMediaTypeKey";
    
    [super didReceiveNotificationRequest:request withContentHandler:contentHandler];
}

@end

Can anyone please guide. 
![IMG_0339](https://user-images.githubusercontent.com/63088322/99381524-42549180-28f1-11eb-886b-facd6563da29.png)

**Comment by Aditi3** [comment]
Please check #14 , looks similar.
