### ISSUE TITLE
No such module 'CTNotificationService'

### ISSUE THREAD

**Issue by amandevthb** [CleverTap/CTNotificationService#23]
![Screenshot 2021-10-20 at 8 52 46 AM](https://user-images.githubusercontent.com/53342739/138023116-a589f1cc-53e3-4e25-bf95-31197990a40b.png
![Screenshot 2021-10-20 at 8 52 41 AM](https://user-images.githubusercontent.com/53342739/138023128-ce909d82-fa3a-4644-89d4-f2314fbc828f.png)
)

**Comment by Aditi3** [comment]
Hi @amandevthb 

Did you try running `pod install`? Example project seems to be working fine at our end. 

<img width="1432" alt="CTNotificationService" src="https://user-images.githubusercontent.com/11608002/138218536-3dfd57b0-9d18-4e58-870d-a1559693ba3b.png">

**Comment by maxim-ivanchuk-idf** [comment]
@Aditi3 your solution now work
i wrote a lot of commands, such as _ pod deintegrate, pod install,pod install --repo-update, pod update  _ but nothing help
i attach here screenshots https://github.com/CleverTap/CTNotificationService/issues/29
