### ISSUE TITLE
Image not showing in push notification

### ISSUE THREAD

**Issue by bajrangsharma-burrp** [CleverTap/CTNotificationService#3]
Hi,

In iOS, on some devices notification image not showing...Plz let we know what went wrong for the same.

showing in iOS version: 11.4.1 but not showing in iOS version: 11.2.5,

CleverTap sdk version: "clevertap-react-native": "^0.2.1",

If available provide me "react-native" clevertap push notification demo app...

**Comment by Aditi3** [comment]
Hey @bajrangsharma-burrp 

Can you verify the Deployment Target of the Notification Service Extension in your project. That extension's deployment target must be at least 10.0 or greater.

You can check the same by following steps:

In Xcode, go to your Targets, under your Notification Service Extension’s name, select General and find Deployment Info and check the value of the Deployment Target.

**Comment by bajrangsharma-burrp** [comment]
Working fine after change target...

**Comment by Aditi3** [comment]
Glad to know it worked for you.

Closing it.

**Comment by Arun-paramasivam** [comment]
Hi,
I'm using
- clevertap-react-native (0.4.5):
    - CleverTap-iOS-SDK (~> 3.8.2)
    - React
  - CTNotificationService (0.1.2)

I'm receiving push notifications in both android and ios. But push with images works only on android. In iOS I receive a notification but the image is not shown. The title of the message comes as 'Test Push [modified]'. Some extra data is coming but not sure why the image is not shown. 
Have set the deployment target of the Notification Service Extension file as 10.0. And I'm testing it on iPhone 6 with ios 13.7.
[
![WhatsApp Image 2020-09-26 at 11 16 10 PM](https://user-images.githubusercontent.com/17449780/94347022-77a9d500-004e-11eb-8c25-c6aabc0f5d9b.jpeg)
](url)
