### ISSUE TITLE
iOS Rich Push Notifications delegates are not calling & content is not showing.

### ISSUE THREAD

**Issue by akhandiOSDev** [CleverTap/CTNotificationService#30]
@Aditi3 Happy Independence from India 🇮🇳 

I am facing an issue while implementing `iOS Rich Push Notifications
Implemented all the steps properly also two individuals identifier for notification on Apple developer account. 

Added an app group & Pust Notification capability. Removed viewController from MainInterface and added View as per documentation

Also, you can check the attachment for the implementation.

But when I triggered the notification through `.apns` file content on the simulator there is no methods or delegates getting triggered.

**Please guide me on what I am missing any steps or doing wrong.**

**Comment by akhandiOSDev** [comment]
@Aditi3 @akashvercetti @AishwaryaNanna need your input?

**Comment by akhandiOSDev** [comment]
@Aditi3 @akashvercetti @AishwaryaNanna  Buttons are showing but **Carousel** Rich notifications content is not showing

**Comment by akhandiOSDev** [comment]
Hey, @AishwaryaNanna Please assist me with this it's a priority task thing I need to finish ASAP.

**Comment by AishwaryaNanna** [comment]
Hi @akhandiOSDev ,
Can please share screenshot of the notification received to check what exactly is receiving and what not?

**Comment by akhandiOSDev** [comment]
Thanks @AishwaryaNanna for your assistance. Please find the below screenshot 

- For Single media, it's working 
- For the `carousels`, I am not able to see the content.

![IMG_0096](https://github.com/CleverTap/CTNotificationService/assets/142230987/c0de1e22-5130-4009-8a27-1d5c1e00fb5f)
![IMG_0093](https://github.com/CleverTap/CTNotificationService/assets/142230987/034755b7-80c0-421e-84ba-4f357fbb0e5f)

Thanks!

**Comment by AishwaryaNanna** [comment]
Hi @akhandiOSDev ,

- For `Carousel` template , you need to mention `"category":"CTNotification"` in the payload 
- Also try the same scenario on device 

Let me know me that works,

Thanks!

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna  I already mentioned `"category":"CTNotification"` in the payload & these above screenshots from the device. I am testing on a real device. 


<img width="1311" alt="Screenshot 2023-08-17 at 12 46 51 PM" src="https://github.com/CleverTap/CTNotificationService/assets/142230987/b84a2029-8d42-4175-9451-bfd814857c73">

**Comment by AishwaryaNanna** [comment]
@akhandiOSDev 

- I could see `App Transport Security Settings -> Allow Arbitrary Loads -> true` is not added in the plist [See plist example here](https://github.com/CleverTap/CTNotificationContent/blob/master/Example/NotificationContent/Info.plist).
- Please check out our sample app and compare if you have added all the mentioned details 
- Try using .png or .jpg files 
- Please share the JSON key value pairs/payload as well for the mentioned Carousal Push template 

Thanks!

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna okay Let me check and update you. 

For point 4

-  Please share the JSON key-value pairs/payload as well for the mentioned Carousal Push template

How I can get JSON key-value pairs/payload because I am triggering from the clever tap dashboard?

**Comment by AishwaryaNanna** [comment]
@akhandiOSDev 

Also please share,

- SDK versions you are using - Clevertap-ios-sdk , CTNotification 

 Enable debug logs and you will get payload as response which you can share.

 Meanwhile try running our sample app after updating with your account id and bundle id with the same payload and see if it is working fine or not.
 
 Thanks!

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna please find the pods version 

  - CTNotificationContent (0.2.4)
  - CTNotificationService (0.1.5)
  - CleverTap-iOS-SDK (4.2.2)
  
after setting `App Transport Security Settings -> Allow Arbitrary Loads -> true` & using .png or .jpg files behavior is still the same
![IMG_C6C04F3D5722-1](https://github.com/CleverTap/CTNotificationService/assets/142230987/a4fc1fb9-bb87-4b7e-abba-a2dd882e1798)

Thanks!!!

**Comment by AishwaryaNanna** [comment]
Hi @akhandiOSDev ,

- Please update Clevertap-iOS-SDK to latest version 
- Please share payload for the Carousel template so that we can test from our side 
- Please try same scenario with our sample app after updating with your account id and bundle id with the same payload and see if it is working fine or not.
- Please share the image urls which you are using in the template 

Please try and follow all the above mentioned points and let me know if anything works.

Thanks!

**Comment by akhandiOSDev** [comment]
Hi @AishwaryaNanna Getting below payload data while tapping on notifications but not seeing UI for carousel on Notification banner.


```

{"W$pivot":"wzrk_default","W$dt":"APPLE","ct_ContentSlider":"{\"orientation\":\"Portrait\",\"showsPaging\":1,\"autoPlay\":1,\"autoDismiss\":0,\"type\":\"carousalImg\",\"items\":[{\"imageUrl\":\"https:\/\/db7hsdc8829us.cloudfront.net\/dist\/1564569217\/i\/14bf21e6a0934dc298d00ef34cba5b67.jpeg?v=1692258314\",\"caption\":\"Cafu CW 🚗\",\"subcaption\":\"Get 50$ off 👌🏼\",\"actionUrl\":\"https:\/\/www.cafu.com\/\"},{\"imageUrl\":\"https:\/\/db7hsdc8829us.cloudfront.net\/dist\/1564569217\/i\/a5b3b10f3c564eab8a47ded5491d6123.jpeg?v=1692258334\",\"caption\":\"Cafu BS 🔋\",\"subcaption\":\"Get 50% cashback 👍\",\"actionUrl\":\"https:\/\/www.cafu.com\/\"}]}","wzrk_acct_id":"TEST-7ZR-965-465Z","W$rnv":true,"W$id":"1692336466_20230818","aps":{"badge":5,"mutable-content":1,"alert":{"title":"Mid Night sale😍","body":"Get 50% off 👍"},"category":"CTNotification","sound":"default"}}


2023-08-18 10:58:45.389773+0530 Cafu[10538:774480] [CleverTap]: Handling notification: {
    "W$dt" = APPLE;
    "W$id" = "1692336466_20230818";
    "W$pivot" = "wzrk_default";
    "W$rnv" = 1;
    aps =     {
        alert =         {
            body = "Get 50% off \Ud83d\Udc4d";
            title = "Mid Night sale\Ud83d\Ude0d";
        };
        badge = 5;
        category = CTNotification;
        "mutable-content" = 1;
        sound = default;
    };
    "ct_ContentSlider" = "{\"orientation\":\"Portrait\",\"showsPaging\":1,\"autoPlay\":1,\"autoDismiss\":0,\"type\":\"carousalImg\",\"items\":[{\"imageUrl\":\"https://db7hsdc8829us.cloudfront.net/dist/1564569217/i/14bf21e6a0934dc298d00ef34cba5b67.jpeg?v=1692258314\",\"caption\":\"Cafu CW \Ud83d\Ude97\",\"subcaption\":\"Get 50$ off \Ud83d\Udc4c\Ud83c\Udffc\",\"actionUrl\":\"https://www.cafu.com/\"},{\"imageUrl\":\"https://db7hsdc8829us.cloudfront.net/dist/1564569217/i/a5b3b10f3c564eab8a47ded5491d6123.jpeg?v=1692258334\",\"caption\":\"Cafu BS \Ud83d\Udd0b\",\"subcaption\":\"Get 50% cashback \Ud83d\Udc4d\",\"actionUrl\":\"https://www.cafu.com/\"}]}";
    "wzrk_acct_id" = "TEST-7ZR-965-465Z";
}
```

Thanks!!!

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna find the image URLs also tested with uploading .png, & jpg images

- 
- https://fastly.picsum.photos/id/11/2500/1667.jpg?hmac=xxjFJtAPgshYkysU_aqx2sZir-kIOjNR9vx0te7GycQ
- https://fastly.picsum.photos/id/13/2500/1667.jpg?hmac=SoX9UoHhN8HyklRA4A3vcCWJMVtiBXUg0W4ljWTor7s

**Comment by akhandiOSDev** [comment]
Hi @AishwaryaNanna Also updated pod `CleverTap-iOS-SDK 4.2.2` but am still not able to see carousel images 

 CleverTap.TEST-7ZR-965-465Z: handling push notification: {
    "W$dt" = APPLE;
    "W$id" = "1692338331_20230818";
    "W$pivot" = "wzrk_default";
    "W$rnv" = 1;
    aps =     {
        alert =         {
            body = "Hello Cafu";
            title = "Flagship sale!!!";
        };
        badge = 2;
        category = CTNotification;
        "mutable-content" = 1;
        sound = default;
    };
    "ct_ContentSlider" = "{\"orientation\":\"Portrait\",\"showsPaging\":1,\"autoPlay\":1,\"autoDismiss\":0,\"type\":\"carousalImg\",\"items\":[{\"imageUrl\":\"https://fastly.picsum.photos/id/11/2500/1667.jpg?hmac=xxjFJtAPgshYkysU_aqx2sZir-kIOjNR9vx0te7GycQ\",\"caption\":\"Cafu Fuel service\",\"subcaption\":\"Get 50% off\Ud83d\Ude0a\",\"actionUrl\":\"https://www.cafu.com/\"},{\"imageUrl\":\"https://fastly.picsum.photos/id/13/2500/1667.jpg?hmac=SoX9UoHhN8HyklRA4A3vcCWJMVtiBXUg0W4ljWTor7s\",\"caption\":\"CAFU BS\",\"subcaption\":\"Get 20% Cashback \Ud83d\Udc4d\Ud83c\Udffc\",\"actionUrl\":\"https://www.cafu.com/\"}]}";
    "wzrk_acct_id" = "TEST-7ZR-965-465Z";
}

Thanks!

**Comment by AishwaryaNanna** [comment]
Hi @akhandiOSDev , 
The above mentioned payload is working perfectly fine with our sample app 
PFA,

Payload:
`{
  "Simulator Target Bundle": "com.clevertap.CTNotificationContentExample",
  "W$dt" : "APPLE",
  "W$id" : "0_0",
  "W$pivot" : "wzrk_default",
  "W$rnv" : 1,
  "aps" :   {
    "alert" :     {
      "body" : "Hello Cafu",
      "title" : "Flagship sale!!!",
    },
    "badge":2,
    "category" : "CTNotification",
    "mutable-content" : 1,
    "sound":"default"
  },
  
  "ct_ContentSlider" : "{\"orientation\":\"Portrait\",\"showsPaging\":1,\"autoPlay\":1,\"autoDismiss\":0,\"type\":\"carousalImg\",\"items\":[{\"imageUrl\":\"https://fastly.picsum.photos/id/11/2500/1667.jpg?hmac=xxjFJtAPgshYkysU_aqx2sZir-kIOjNR9vx0te7GycQ\",\"caption\":\"Cafu Fuel service\",\"subcaption\":\"Get 50% off\",\"actionUrl\":\"https://www.cafu.com/\"},{\"imageUrl\":\"https://fastly.picsum.photos/id/13/2500/1667.jpg?hmac=SoX9UoHhN8HyklRA4A3vcCWJMVtiBXUg0W4ljWTor7s\",\"caption\":\"CAFU BS\",\"subcaption\":\"Get 20% Cashback\",\"actionUrl\":\"https://www.cafu.com/\"}]}",
  "wzrk_acct_id" : "W9R-486-4W5Z",
}`

Notification screenshot:
![simulator_screenshot_D818A78C-6AFF-47C1-BDEB-A3127F8C9D0F](https://github.com/CleverTap/CTNotificationService/assets/97506871/c2381737-db23-4d72-aa78-d6b7d17b4355)

Please check out our [Sample App](https://github.com/CleverTap/CTNotificationContent#sample-app) and compare with your implementation. 

Thanks!

**Comment by nishant-clevertap** [comment]
Hi @akhandiOSDev,
It seems you are having emoji glitch, try sending push without emoji and it will render successfully. Also refer the payload shared by @AishwaryaNanna in above comment.

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna is it working with the carousel?

**Comment by AishwaryaNanna** [comment]
@akhandiOSDev , 
Yes, its with carousel.
Please try carousel push without any emoji’s 

https://github.com/CleverTap/CTNotificationService/assets/97506871/50b4d177-c58e-4603-a993-2476e6586dce

Thanks!

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna I tried the same scenario with the sample app after updating with `account id` `token` and `bundle id` with the same payload. It is working fine. 

Then I updated my `NotificationService` & `NotificationContent` through the sample app .plist but still at my side facing the same issue. I also match the whole implementation with sample apps multiple times seems okay to me. 

@nishant-clevertap @AishwaryaNanna Guys can we have a call for some time might be you guys able to identify the glitch.  It's a priority thing to me. 

Thanks!

**Comment by AishwaryaNanna** [comment]
@akhandiOSDev 
Did you try removing emoji’s from the title/subtitle and trigger carousel notification?

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna Yes, I did that also even I tried with the given payload which is working in the sample app but still getting the same issue.

**Comment by AishwaryaNanna** [comment]
Hi @akhandiOSDev ,

Please raise a ticket through the CleverTap dashboard, our Technical Account Managers can take a closer look at it.

Thanks!

**Comment by akhandiOSDev** [comment]
Hi, @nishant-clevertap @AishwaryaNanna Guys please do one last input please find the added `.zip` file for the sample app which I created I just copy paste all the content which is working in the Clevertap sample app. 

But still getting the same issue even whole code is the same as the sample app. 

Guys, please do a quick review there are only very few lines of code and a few files. 
```
{
  "Simulator Target Bundle": "com.clevertap.CTNotificationContentExample",
  "W$dt" : "APPLE",
  "W$id" : "0_0",
  "W$pivot" : "wzrk_default",
  "W$rnv" : 1,
  "aps" :   {
    "alert" :     {
      "body" : "Hello Cafu",
      "title" : "Flagship sale!!!",
    },
    "badge":2,
    "category" : "CTNotification",
    "mutable-content" : 1,
    "sound":"default"
  },
  
  "ct_ContentSlider" : "{\"orientation\":\"Portrait\",\"showsPaging\":1,\"autoPlay\":1,\"autoDismiss\":0,\"type\":\"carousalImg\",\"items\":[{\"imageUrl\":\"https://fastly.picsum.photos/id/11/2500/1667.jpg?hmac=xxjFJtAPgshYkysU_aqx2sZir-kIOjNR9vx0te7GycQ\",\"caption\":\"Cafu Fuel service\",\"subcaption\":\"Get 50% off\",\"actionUrl\":\"https://www.cafu.com/\"},{\"imageUrl\":\"https://fastly.picsum.photos/id/13/2500/1667.jpg?hmac=SoX9UoHhN8HyklRA4A3vcCWJMVtiBXUg0W4ljWTor7s\",\"caption\":\"CAFU BS\",\"subcaption\":\"Get 20% Cashback\",\"actionUrl\":\"https://www.cafu.com/\"}]}",
  "wzrk_acct_id" : "W9R-486-4W5Z",
}
```

[CTNotificationDemo.zip](https://github.com/CleverTap/CTNotificationService/files/12379085/CTNotificationDemo.zip)

**Comment by akhandiOSDev** [comment]
@nishant-clevertap @AishwaryaNanna Guys please review this `.zip Sample app` from the attachment and let me know where I am missing in setup. 

Thanks!

**Comment by akhandiOSDev** [comment]
Hey, @AishwaryaNanna @nishant-clevertap any update on `CTNotificationDemo.zip`? Please review once I copied the same codebase in that but that one is not working with the given payload.

Thanks!

**Comment by akhandiOSDev** [comment]
Hey, @AishwaryaNanna Please have a look at it.

Thanks!

**Comment by AishwaryaNanna** [comment]
Hi @akhandiOSDev ,

We have checked your demo project and it seems to be issue with your MainInterface storyboard for the NotificationContent target. Make sure the `is Initial view controller` checkbox is enabled when you copy/replace the storyboard file, by default when you create notification target it is enabled.

Refer following screenshot for your reference you can find it under Attributes Inspector in Xcode,

<img width="1012" alt="Screenshot 2023-08-21 at 4 35 26 PM" src="https://github.com/CleverTap/CTNotificationService/assets/97506871/423900d5-4983-45c8-90d3-0f9be189ebbd">

After enabling it on your demo project, notification is rendering successfully.

Let me know if it works,

Thanks!

**Comment by akhandiOSDev** [comment]
@AishwaryaNanna Thanks, Yes your technical manager Karthik connected on It and shared the same.  Please also include this in your documentation.

Guys, one thing I want to know: No delegates are calling on tap `View In App`. 

Please let me know how I can get notification calls in the app and the action accordingly.

Thanks!

**Comment by AishwaryaNanna** [comment]
@akhandiOSDev 
As the solution worked for you and issue got resolved , closing this.

Thanks!
