### ISSUE TITLE
Can we fetch location at notification receiving time

### ISSUE THREAD

**Issue by bajrangsharma-burrp** [CleverTap/CTNotificationService#4]
Hi,

**How can we get location geo at the time of notification receive and send to server even when app is closed???.** or **How can we send silent notification to wakeup the App?? in Android.**

**If any solution for the same...Plz let we know...**

**Comment by Aditi3** [comment]
Hi @bajrangsharma-burrp 

I am assuming that you wish to track the geolocation as soon as the user receives the notification using CleverTap. 

This is something that needs to be implemented at your end. However, if you any further query you can definitely reach out to support@clevertap.com.

**Comment by bajrangsharma-burrp** [comment]
Thanks for quick update...sure I will mail my queries...

**Comment by bajrangsharma-burrp** [comment]
**What type of implementation we need to implement at App end to achieve the goal**?...

**Comment by bajrangsharma-burrp** [comment]
Any hope for this logic...

**Comment by Aditi3** [comment]
hey @bajrangsharma-burrp 

Apologies! Would request you to write to support@clevertap.com to take the discussion forward.

Thanks!
