### ISSUE TITLE
unknown type name 'FOUNDATION_EXPORT' in CTNotificationService.h

### ISSUE THREAD

**Issue by hb2708** [CleverTap/CTNotificationService#7]
Hello While integrating this in our app facing the following errors

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/13498448/72490751-05dc8300-3853-11ea-8a68-5d342c7456f2.png">

Replacing `FOUNDATION_EXPORT` with `extern` seems to work as expected.

**Environment we faced the issue is**
Xcode Version 11.3 (11C29)
Xcode 10.3.x

**Comment by hb2708** [comment]
Some evidence that it works https://github.com/aleclarson/emitter-kit/issues/17#issue-84564033

**Comment by hb2708** [comment]
@Aditi3

**Comment by Aditi3** [comment]
Hey @hb2708 

Acknowledged. Please allow me some time to re-check the same at my end and I will get back to you with an update shortly.

**Comment by hb2708** [comment]
Hello @Aditi3 

Yes sure.

**Comment by Aditi3** [comment]
Hey @hb2708 

We have released the CTNotificationService to handle the mentioned errors.

Here is the link to the latest release that comes with the changes suggested.
https://github.com/CleverTap/CTNotificationService/releases/tag/0.1.2

Thanks for your patience.

**Comment by hb2708** [comment]
Thanks for the release
